/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as PerfisRouteImport } from './routes/perfis'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAparenciaRouteImport } from './routes/admin.aparencia'
import { Route as AdminCatalogoRouteImport } from './routes/admin.catalogo'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminDestaquesRouteImport } from './routes/admin.destaques'
import { Route as AdminEpisodiosRouteImport } from './routes/admin.episodios'
import { Route as AdminFileirasRouteImport } from './routes/admin.fileiras'
import { Route as AdminMidiaRouteImport } from './routes/admin.midia'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminRodapeRouteImport } from './routes/admin.rodape'
import { Route as HistoriaSlugRouteImport } from './routes/historia.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfisRoute = PerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAparenciaRoute = AdminAparenciaRouteImport.update({
  id: '/aparencia',
  path: '/aparencia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogoRoute = AdminCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDestaquesRoute = AdminDestaquesRouteImport.update({
  id: '/destaques',
  path: '/destaques',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEpisodiosRoute = AdminEpisodiosRouteImport.update({
  id: '/episodios',
  path: '/episodios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFileirasRoute = AdminFileirasRouteImport.update({
  id: '/fileiras',
  path: '/fileiras',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMidiaRoute = AdminMidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRodapeRoute = AdminRodapeRouteImport.update({
  id: '/rodape',
  path: '/rodape',
  getParentRoute: () => AdminRoute,
} as any)
const HistoriaSlugRoute = HistoriaSlugRouteImport.update({
  id: '/historia/$slug',
  path: '/historia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/conta': typeof ContaRoute
  '/perfis': typeof PerfisRoute
  '/admin/aparencia': typeof AdminAparenciaRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/destaques': typeof AdminDestaquesRoute
  '/admin/episodios': typeof AdminEpisodiosRoute
  '/admin/fileiras': typeof AdminFileirasRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/rodape': typeof AdminRodapeRoute
  '/historia/$slug': typeof HistoriaSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conta': typeof ContaRoute
  '/perfis': typeof PerfisRoute
  '/admin/aparencia': typeof AdminAparenciaRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/destaques': typeof AdminDestaquesRoute
  '/admin/episodios': typeof AdminEpisodiosRoute
  '/admin/fileiras': typeof AdminFileirasRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/rodape': typeof AdminRodapeRoute
  '/historia/$slug': typeof HistoriaSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/conta': typeof ContaRoute
  '/perfis': typeof PerfisRoute
  '/admin/aparencia': typeof AdminAparenciaRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/destaques': typeof AdminDestaquesRoute
  '/admin/episodios': typeof AdminEpisodiosRoute
  '/admin/fileiras': typeof AdminFileirasRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/rodape': typeof AdminRodapeRoute
  '/historia/$slug': typeof HistoriaSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/conta'
    | '/perfis'
    | '/admin/aparencia'
    | '/admin/catalogo'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/destaques'
    | '/admin/episodios'
    | '/admin/fileiras'
    | '/admin/midia'
    | '/admin/planos'
    | '/admin/rodape'
    | '/historia/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/conta'
    | '/perfis'
    | '/admin/aparencia'
    | '/admin/catalogo'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/destaques'
    | '/admin/episodios'
    | '/admin/fileiras'
    | '/admin/midia'
    | '/admin/planos'
    | '/admin/rodape'
    | '/historia/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/conta'
    | '/perfis'
    | '/admin/aparencia'
    | '/admin/catalogo'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/destaques'
    | '/admin/episodios'
    | '/admin/fileiras'
    | '/admin/midia'
    | '/admin/planos'
    | '/admin/rodape'
    | '/historia/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContaRoute: typeof ContaRoute
  PerfisRoute: typeof PerfisRoute
  HistoriaSlugRoute: typeof HistoriaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfis': {
      id: '/perfis'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof PerfisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/aparencia': {
      id: '/admin/aparencia'
      path: '/aparencia'
      fullPath: '/admin/aparencia'
      preLoaderRoute: typeof AdminAparenciaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogo': {
      id: '/admin/catalogo'
      path: '/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AdminCatalogoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/destaques': {
      id: '/admin/destaques'
      path: '/destaques'
      fullPath: '/admin/destaques'
      preLoaderRoute: typeof AdminDestaquesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/episodios': {
      id: '/admin/episodios'
      path: '/episodios'
      fullPath: '/admin/episodios'
      preLoaderRoute: typeof AdminEpisodiosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fileiras': {
      id: '/admin/fileiras'
      path: '/fileiras'
      fullPath: '/admin/fileiras'
      preLoaderRoute: typeof AdminFileirasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/midia': {
      id: '/admin/midia'
      path: '/midia'
      fullPath: '/admin/midia'
      preLoaderRoute: typeof AdminMidiaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rodape': {
      id: '/admin/rodape'
      path: '/rodape'
      fullPath: '/admin/rodape'
      preLoaderRoute: typeof AdminRodapeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/historia/$slug': {
      id: '/historia/$slug'
      path: '/historia/$slug'
      fullPath: '/historia/$slug'
      preLoaderRoute: typeof HistoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAparenciaRoute: typeof AdminAparenciaRoute
  AdminCatalogoRoute: typeof AdminCatalogoRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminDestaquesRoute: typeof AdminDestaquesRoute
  AdminEpisodiosRoute: typeof AdminEpisodiosRoute
  AdminFileirasRoute: typeof AdminFileirasRoute
  AdminMidiaRoute: typeof AdminMidiaRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminRodapeRoute: typeof AdminRodapeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAparenciaRoute: AdminAparenciaRoute,
  AdminCatalogoRoute: AdminCatalogoRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminDestaquesRoute: AdminDestaquesRoute,
  AdminEpisodiosRoute: AdminEpisodiosRoute,
  AdminFileirasRoute: AdminFileirasRoute,
  AdminMidiaRoute: AdminMidiaRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminRodapeRoute: AdminRodapeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContaRoute: ContaRoute,
  PerfisRoute: PerfisRoute,
  HistoriaSlugRoute: HistoriaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
